require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 4.2

Layout/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/**/*'

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'test/**/*'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
