---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/HashAsLastArrayItem:
  Exclude:
  - spec/lib/redmine_nonproject_modules/patches/redmine/menu_manager_mapper_patch_spec.rb
Style/HashConversion:
  Exclude:
  - spec/models/group_permission_spec.rb
Style/OptionalBooleanParameter:
  Exclude:
  - app/models/group_permission.rb
Style/RedundantConstantBase:
  Exclude:
  - app/models/group_merge.rb
  - config/initializers/group_permissions.rb
  - init.rb
  - lib/redmine_nonproject_modules/patches/group_patch.rb
  - lib/redmine_nonproject_modules/patches/redmine/i18n_patch.rb
  - lib/redmine_nonproject_modules/patches/redmine/menu_manager_patch.rb
  - lib/redmine_nonproject_modules/patches/redmine/plugin.rb
  - lib/redmine_nonproject_modules/patches/user_patch.rb
  - lib/tasks/redmine_nonproject_modules.rake
  - redmine_nonproject_modules.gemspec
  - spec/lib/redmine_nonproject_modules/patches/redmine/menu_manager_mapper_patch_spec.rb
  - spec/models/group_merge_spec.rb
  - spec/models/group_permission_spec.rb
